[package]
name = "hello"
version = "0.1.0"
authors = ["E185574L <lou-anne.sauvetre@etu.univ-nantes.fr>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.75"
